ability to set group and item draggability independently
AppFlowy-IO/appflowy-board pull request #6
Opened 2023-04-06 20:06 UTC by corey-fuller

2023-04-06 20:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AppFlowy-IO/appflowy-board?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AppFlowy-IO/appflowy-board?pullRequest=6) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AppFlowy-IO/appflowy-board?pullRequest=6) it.</sub>

2023-04-13 10:59 UTC, appflowy commented
@corey-fuller  Thanks for contribution. I will check it.

2023-11-06 09:36 UTC, Xazin requested changes

2023-11-06 09:36 UTC, Xazin commented on lib/src/widgets/board_data.dart
> +    for (var groupController in _groupControllers.values) {
```suggestion
    for (final groupController in _groupControllers.values) {
```

2023-11-06 09:36 UTC, Xazin commented on lib/src/widgets/board_group/group_data.dart
> +    for (var item in groupData._items) {
```suggestion
    for (final item in groupData._items) {
```

2023-11-06 09:36 UTC, Xazin commented on lib/src/widgets/board_group/group_data.dart
> +  void setDraggability(bool groupDragging, itemDragging) {
Can we add document comment for this method,.

2023-11-06 09:37 UTC, Xazin commented
Hey @corey-fuller, sorry about the delay.

Are you interested in finishing this PR? I've added some minor comments above, and I'd also need you to sign the CLA (see the first comment in the PR).

2024-02-15 11:12 UTC, closed without merging